//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APKToolGUI.Languages {
    using System;

        /// <summary>
        /// <summary>
        ///   Looks up a localized string similar to APK Installation failed.
        /// </summary>
        internal static string InstallApkFailed {
            get {
                return ResourceManager.GetString("InstallApkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK Installation successfully.
        /// </summary>
        internal static string InstallApkSuccessful {
            get {
                return ResourceManager.GetString("InstallApkSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install framework.
        /// </summary>
        internal static string InstallFramework {
            get {
                return ResourceManager.GetString("InstallFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing APK.
        /// </summary>
        internal static string InstallingApk {
            get {
                return ResourceManager.GetString("InstallingApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing APK &quot;{0}&quot;.
        /// </summary>
        internal static string InstallingApkPath {
            get {
                return ResourceManager.GetString("InstallingApkPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing framework.
        /// </summary>
        internal static string InstallingFramework {
            get {
                return ResourceManager.GetString("InstallingFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main activity found in &quot;{0}&quot;.
        /// </summary>
        internal static string MainActivityFound {
            get {
                return ResourceManager.GetString("MainActivityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find MainActivity. Please find it manually.
        /// </summary>
        internal static string MainActivityNotFoundPleaseFindManually {
            get {
                return ResourceManager.GetString("MainActivityNotFoundPleaseFindManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge finished. Moving directory to &quot;{0}&quot;.
        /// </summary>
        internal static string MergeFinishedMoveDir {
            get {
                return ResourceManager.GetString("MergeFinishedMoveDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging APK.
        /// </summary>
        internal static string MergingApk {
            get {
                return ResourceManager.GetString("MergingApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging APK using APKEditor.jar.
        /// </summary>
        internal static string MergingApkEditor {
            get {
                return ResourceManager.GetString("MergingApkEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to META-INF folder does not exist. Skipped.
        /// </summary>
        internal static string MetainfNotExist {
            get {
                return ResourceManager.GetString("MetainfNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move temp folder &quot;{0}&quot; to output directory &quot;{1}&quot;.
        /// </summary>
        internal static string MoveTempApkFileToOutput {
            get {
                return ResourceManager.GetString("MoveTempApkFileToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move temp apk &quot;{0}&quot; to output directory &quot;{1}&quot;.
        /// </summary>
        internal static string MoveTempApkToOutput {
            get {
                return ResourceManager.GetString("MoveTempApkToOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving base directory to &quot;{0}&quot;.
        /// </summary>
        internal static string MovingBasedirectory {
            get {
                return ResourceManager.GetString("MovingBasedirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the changes to take effect you must restart the program. You want to do it now?.
        /// </summary>
        internal static string NeedRestart {
            get {
                return ResourceManager.GetString("NeedRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices found. Make sure your device is connected to the computer with the adb debugging turned on. If you use an emulator, restart it and wait until it boot up.
        /// </summary>
        internal static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not a decompiled APK.
        /// </summary>
        internal static string NotDecompiledApk {
            get {
                return ResourceManager.GetString("NotDecompiledApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder is not a decompiled DEX.
        /// </summary>
        internal static string NotDecompiledDex {
            get {
                return ResourceManager.GetString("NotDecompiledDex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open compile output folder.
        /// </summary>
        internal static string OpenComFolder {
            get {
                return ResourceManager.GetString("OpenComFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open decompile output folder.
        /// </summary>
        internal static string OpenDecFolder {
            get {
                return ResourceManager.GetString("OpenDecFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing APK Info....
        /// </summary>
        internal static string ParsingApkInfo {
            get {
                return ResourceManager.GetString("ParsingApkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed all ApkTool dummies.
        /// </summary>
        internal static string RemoveApkToolDummies {
            get {
                return ResourceManager.GetString("RemoveApkToolDummies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required files are missing.
        /// </summary>
        internal static string RequiredFilesMissing {
            get {
                return ResourceManager.GetString("RequiredFilesMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart is required to apply changes. Do you want to restart the application?.
        /// </summary>
        internal static string RestartApplicationPrompt {
            get {
                return ResourceManager.GetString("RestartApplicationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SetLanguageRestartApplication {
            get {
                return ResourceManager.GetString("SetLanguageRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        internal static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign APK.
        /// </summary>
        internal static string SignApk {
            get {
                return ResourceManager.GetString("SignApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing.
        /// </summary>
        internal static string Signing {
            get {
                return ResourceManager.GetString("Signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file not found..
        /// </summary>
        internal static string SignInputFileNotFound {
            get {
                return ResourceManager.GetString("SignInputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key not found..
        /// </summary>
        internal static string SignPrivateKeyNotFound {
            get {
                return ResourceManager.GetString("SignPrivateKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key not found..
        /// </summary>
        internal static string SignPublicKeyNotFound {
            get {
                return ResourceManager.GetString("SignPublicKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing successfully completed. File saved to &quot;{0}&quot;..
        /// </summary>
        internal static string SignSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("SignSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smali.
        /// </summary>
        internal static string Smali {
            get {
                return ResourceManager.GetString("Smali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split APK is not selected.
        /// </summary>
        internal static string SplitApkNotFound {
            get {
                return ResourceManager.GetString("SplitApkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System language.
        /// </summary>
        internal static string SystemLanguage {
            get {
                return ResourceManager.GetString("SystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp directory: &quot;{0}&quot;.
        /// </summary>
        internal static string TempDirectory {
            get {
                return ResourceManager.GetString("TempDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text file.
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time ended: {0}.
        /// </summary>
        internal static string TimeEnded {
            get {
                return ResourceManager.GetString("TimeEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time started: {0}.
        /// </summary>
        internal static string TimeStarted {
            get {
                return ResourceManager.GetString("TimeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available. Do you want to update?.
        /// </summary>
        internal static string UpdateNewVersion {
            get {
                return ResourceManager.GetString("UpdateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update is available..
        /// </summary>
        internal static string UpdateNoUpdates {
            get {
                return ResourceManager.GetString("UpdateNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoding folder not selected!.
        /// </summary>
        internal static string WarningDecodingFolderNotSelected {
            get {
                return ResourceManager.GetString("WarningDecodingFolderNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File for decoding not selected!.
        /// </summary>
        internal static string WarningFileForDecodingNotSelected {
            get {
                return ResourceManager.GetString("WarningFileForDecodingNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File for signing not selected!.
        /// </summary>
        internal static string WarningFileForSigningNotSelected {
            get {
                return ResourceManager.GetString("WarningFileForSigningNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Framework not selected!.
        /// </summary>
        internal static string WarningFrameworkNotSelected {
            get {
                return ResourceManager.GetString("WarningFrameworkNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipalign.
        /// </summary>
        internal static string Zipalign {
            get {
                return ResourceManager.GetString("Zipalign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipalign APK.
        /// </summary>
        internal static string ZipalignApk {
            get {
                return ResourceManager.GetString("ZipalignApk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipalign successfully completed. File saved to &quot;{0}&quot;.
        /// </summary>
        internal static string ZipalignFileSavedTo {
            get {
                return ResourceManager.GetString("ZipalignFileSavedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP archives.
        /// </summary>
        internal static string ZIPArchives {
            get {
                return ResourceManager.GetString("ZIPArchives", resourceCulture);
            }
        }
    }
}
